const char *fragmentShaderSource = 
"#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2DArray data1;\n"
"uniform sampler2DArray data2;\n"
"uniform sampler1DArray beam1;\n"
"uniform sampler1DArray beam2;\n"
"uniform sampler1DArray fade1;\n"
"uniform sampler1DArray fade2;\n"
"uniform float contrast;\n"
"uniform float bright;\n"
"uniform float amprange;\n"
"uniform float ampoffset;\n"
"uniform float gamma;\n"
"uniform float rotate;\n"
"uniform int tna;\n"
"uniform int tnd;\n"
"uniform vec4 background;\n"
"uniform vec4 colorr;\n"
"uniform vec4 colorg;\n"
"//uniform float noise;\n"
"\n"
"#define PIx2 6.283185307\n"
"#define PI2 1.570796327\n"
"\n"
"void\n"
"main ()\n"
"{\n"
"  vec2 p, q = vec2 (0.0, 0.0);\n"
"  float r, g, x, y, z1, z2;\n"
"  vec4 c;\n"
"\n"
"  p.x = TexCoord.x * 2.0 - 1.0;\n"
"  p.y = TexCoord.y * 2.0 - 1.0;\n"
"\n"
"  q.x = length (p);\n"
"  if (q.x >= 1.0)\n"
"    discard;\n"
"  if (abs (p.y) > abs (p.x))\n"
"    {\n"
"      q.y = 2.0 * atan (p.x / (q.x + p.y));\n"
"    }\n"
"  else if (abs (p.x) > abs (p.y))\n"
"    {\n"
"      q.y = PI2 - 2.0 * atan (p.y / (q.x + p.x));\n"
"    }\n"
"  else\n"
"    {\n"
"      q.y = 0.0;\n"
"    }\n"
"  q.y = mod ((q.y + rotate) / PIx2, 1.0) * tna;\n"
"  q.x = q.x * tnd;\n"
"  y = mod (q.y, 1.0);\n"
"  z2 = floor (q.y);\n"
"  z1 = z2 * tnd + floor (q.x);\n"
"  x = mod (q.x, 1.0);\n"
"\n"
"  //q.x += fract(sin(dot(q ,vec2(12.9898,78.233))) * 43758.5453) * (1.0 - q.x) * diskreet;\n"
"  //q.y += (-noise + 2.0 * noise * fract(sin(dot(q ,vec2(12.9898,78.233))) * 43758.5453) * (1.0 - q.y));\n"
"\n"
"  // note: mix(x,y,a) = x*(1-a) + y*a\n"
"\n"
"  r = (texture (data1, vec3 (x, y, z1)).r - ampoffset) * amprange;\n"
"  r = pow (r, gamma);\n"
"  r = bright + contrast * r;\n"
"  c.r = texture (fade1, vec2 (y, z2)).r;\n"
"  r = clamp (r * c.r, 0.0, 1.0);\n"
"\n"
"  g = (texture (data2, vec3 (x, y, z1)).r - ampoffset) * amprange;\n"
"  g = pow (g, gamma);\n"
"  g = bright + contrast * g;\n"
"  c.g = texture (fade2, vec2 (y, z2)).r;\n"
"  g = clamp (g * c.g, 0.0, 1.0);\n"
"\n"
"  if (c.r > c.g)\n"
"    {\n"
"      c = mix (background, colorr, r);\n"
"    }\n"
"  else\n"
"    {\n"
"      c = mix (background, colorg, g);\n"
"    }\n"
"  c = mix (c, colorr, texture (beam1, vec2 (y, z2)).r);\n"
"  c = mix (c, colorg, texture (beam2, vec2 (y, z2)).r);\n"
"  FragColor = c;\n"
"}\n"
;
